/* e-AKHA helper: audit TC all shifts, suppress TH attention, check MC/HRMIS missing. */
(function(){
'use strict';
const P='audit-tc-rules-mc-hrmis-check-april2026-v2';
if(!confirm('Apply audit TIMECARD semua shift + TH/TT tidak flag perhatian + semak MC/HRMIS tertinggal?'))return;
const U=v=>String(v==null?'':v).toUpperCase().replace(/MOHAMMAD|MUHAMMAD|MOHAMED|MOHAMMAAD/g,'MOHAMAD').replace(/\bMUHD\b/g,'MOHD').replace(/[^A-Z0-9 ]+/g,' ').replace(/\s+/g,' ').trim();
const m=(t,ctx)=>{let x=String(t||'').match(/^(\d{1,2}):(\d{2})$/);if(!x)return null;let n=+x[1]*60+ +x[2];return(ctx==='PT'&&n===0)?1440:n};
const ts=a=>(Array.isArray(a)?a:[]).map(String).filter(x=>/^\d{1,2}:\d{2}$/.test(x)).sort((a,b)=>m(a)-m(b));
const win=(a,l,h,ctx)=>ts(a).filter(t=>{let x=m(t,ctx);return x!=null&&x>=l&&x<=h});
const near=(a,t,ctx)=>{a=ts(a);return a.length?a.slice().sort((x,y)=>Math.abs(m(x,ctx)-t)-Math.abs(m(y,ctx)-t))[0]:''};
const days=()=>{try{return typeof daysInActiveMonth==='function'?daysInActiveMonth():30}catch(e){return 30}};
const C=(b,d)=>{if(!D[b])D[b]={};if(!D[b][d])D[b][d]={};return D[b][d]};
function sh(mem,d,c){let s='';try{s=U(typeof gSh==='function'?gSh(mem.bil,d):'')}catch(e){}if(!s)s=U((c&&c.tc_shift)||'');if(/OFF|OFFDAY|\bOF\b|REHAT/.test(s))return'OF';if(/MALAM|NIGHT|\bM\b|2300.*0700/.test(s))return'M';if(/PETANG|\bPT\b|1500.*2300/.test(s))return'PT';if(/PAGI|\bPG\b|0700.*1500/.test(s))return'PG';return s}
const hasTC=c=>!!(c&&(c.tc_in||c.tc_out||(Array.isArray(c.tc_all)&&c.tc_all.length)));
const isTH=c=>/\bTH\b|\bTT\b|TAHAN TUGAS/.test(U([c.kzp,c.kzk,c.audit,c.audit_final,c.note].join(' ')));
const isMC=c=>!!(c&&(c._mc||c.mc_status_51038||c.mc_rule_51038||U(c.mc)==='MC'));
const HR=c=>{let h=U(c&&c.hrmis);return h&&h!=='-'?h:''};
function pair(code,today,next){if(code==='PG')return{inn:win(today,360,425)[0]||near(win(today,330,479),420),out:win(today,900,960)[0]||near(win(today,870,990),900),label:'SHIFT PG (0700-1500)'};if(code==='PT')return{inn:win(today,840,905)[0]||near(win(today,810,959),900),out:win(today,1380,1440,'PT')[0]||near(win(today,1350,1440,'PT'),1380,'PT'),label:'SHIFT PT (1500-2300)'};if(code==='M')return{inn:win(today,1320,1385)[0]||near(win(today,1290,1439),1380),out:win(next,420,480)[0]||near(win(next,390,510),420),label:'SHIFT M (2300-0700)'};return{inn:'',out:'',label:code}}
function stat(code,c,today,next,p){let h=HR(c);if(isTH(c))return['TH/TT - ABAIKAN','TAHAN TUGAS'];if(isMC(c))return['MC SAH','TC tidak wajib'];if(h)return[h,'TC tidak wajib'];if(code==='OF')return[hasTC(c)?'OFFDAY / OT - ABAIKAN':'OFF',''];if(!hasTC(c)&&!today.length)return['ABS - TIADA PUNCH',''];if(!p.inn&&!p.out)return['SEMAK TC - TIADA IN & OUT',''];if(!p.inn)return['SEMAK TC - TIADA IN',''];if(!p.out)return['SEMAK TC - TIADA OUT',''];let im=m(p.inn),om=m(p.out,code==='PT'?'PT':null);if(code==='PG'){if(im>425)return['LEWAT','IN selepas 0705'];if(om<900)return['OUT AWAL','OUT sebelum 1500']}if(code==='PT'){if(im>905)return['LEWAT','IN selepas 1505'];if(om<1380)return['OUT AWAL','OUT sebelum 2300']}if(code==='M'){if(im>1385)return['LEWAT','IN selepas 2305'];if(om<420)return['OUT AWAL','OUT sebelum 0700'];if(om>480)return['SEMAK OUT','OUT selepas 0800']}return['SAH','TC ada IN & OUT']}
function load(k,def){try{return JSON.parse(localStorage.getItem(k)||'')}catch(e){return def}}
function dp(s){let x=String(s||'').match(/(\d{1,2})[\/\-.](\d{1,2})(?:[\/\-.](20\d{2}|\d{2}))?/);if(!x)return null;let y=x[3]?+x[3]:2026;if(y<100)y+=2000;return{d:+x[1],m:+x[2],y}}
function rdates(r){let a=dp(r.tarikh||r.date||r.dari||r.start||r._dari||r.tarikh_mula),b=dp(r.hingga||r.end||r._hingga||r.tarikh_akhir)||a;if(!a)return[];let o=[];if(a.y===b.y&&a.m===b.m){for(let d=a.d;d<=b.d;d++)o.push({d,m:a.m,y:a.y})}else o.push(a);return o.filter(x=>x.m===4&&x.y===2026&&x.d>=1&&x.d<=30)}
function sc(a,b){a=U(a);b=U(b);if(a===b)return 100;if(a.includes(b)||b.includes(a))return 95;let A=a.split(' ').filter(w=>w.length>3&&!/^(BIN|BINTI|MOHD|MOHAMAD)$/.test(w));let h=A.filter(w=>b.split(' ').includes(w)).length;return Math.round(h/Math.max(A.length,1)*100)}
function mem(n){let best={m:null,score:0};(MASTER||[]).forEach(x=>{let s=sc(n,x.nama);if(s>best.score)best={m:x,score:s}});return best.score>=70?best:{m:null,score:best.score}}
const rn=r=>r.nama||r.name||r._nama||r.pemohon||r.applicant||r.staff_name||r.nama_pemohon||'';
if(typeof MASTER==='undefined'||typeof D==='undefined'){alert('Buka Master File April dahulu.');return}
try{localStorage.setItem('eakha_backup_before_'+P+'_'+Date.now(),JSON.stringify(D))}catch(e){}
let counts={SAH:0,LEWAT:0,OUT_AWAL:0,SEMAK:0,ABS:0,IGNORE_TH:0,IGNORE_OFF:0,MC:0,HR:0},sample=[];
(MASTER||[]).forEach(memr=>{for(let d=1;d<=days();d++){let c=C(memr.bil,d),code=sh(memr,d,c),today=ts(c.tc_all),next=ts((D[memr.bil]&&D[memr.bil][d+1]&&D[memr.bil][d+1].tc_all)||[]),p=pair(code,today,next),s=stat(code,c,today,next,p);if(['PG','PT','M'].includes(code)){c.tc_in=p.inn||'';c.tc_out=p.out||'';c.tc_shift=p.label}c.tc_audit_status=s[0];c.tc_issue=s[1];c.tc_audit_patch=P;if(isTH(c)){c.audit_ignore_attention=true;c.no_perhatian=true;if(Array.isArray(c.flags))c.flags=c.flags.filter(f=>!/ABS|TIADA PUNCH|SEMAK TC|TIDAK HADIR/i.test(String(f)))}let key=s[0].includes('LEWAT')?'LEWAT':s[0].includes('OUT AWAL')?'OUT_AWAL':s[0].includes('SEMAK')?'SEMAK':s[0].includes('ABS')?'ABS':s[0].includes('TH')?'IGNORE_TH':s[0].includes('OFFDAY')?'IGNORE_OFF':s[0].includes('MC')?'MC':HR(c)?'HR':s[0]==='SAH'?'SAH':'SEMAK';counts[key]=(counts[key]||0)+1;if((s[0]!=='SAH'&&sample.length<100)||s[0].includes('SEMAK'))sample.push({bil:memr.bil,nama:memr.nama,d,shift:code,status:s[0],issue:s[1],in:c.tc_in,out:c.tc_out,all:today.join(' ')})}});
let ds=load('eakha_dataset_2026_4',{}),MC=(window.MC_DATA&&Array.isArray(window.MC_DATA)?window.MC_DATA:load('eakha_mc',[])||ds.MC_DATA||[]),H=(window.HRMIS_DATA&&Array.isArray(window.HRMIS_DATA)?window.HRMIS_DATA:load('eakha_hrmis',[])||ds.HRMIS_DATA||[]),missingMC=[],missingHR=[],unmatchedMC=[],unmatchedHR=[];
MC.forEach(r=>{let mt=mem(rn(r)),dd=rdates(r);if(!mt.m){unmatchedMC.push({nama:rn(r),score:mt.score});return}dd.forEach(x=>{let c=(D[mt.m.bil]&&D[mt.m.bil][x.d])||{};if(!isMC(c))missingMC.push({bil:mt.m.bil,nama:mt.m.nama,d:x.d,src:rn(r),no_mc:r.no_mc||r.siri||''})})});
H.forEach(r=>{let mt=mem(rn(r)),dd=rdates(r);if(!mt.m){unmatchedHR.push({nama:rn(r),score:mt.score});return}dd.forEach(x=>{let c=(D[mt.m.bil]&&D[mt.m.bil][x.d])||{};if(!HR(c))missingHR.push({bil:mt.m.bil,nama:mt.m.nama,d:x.d,src:rn(r),jenis:r.jenis||r.type||r.leave_type||r._jenis||'HRMIS'})})});
try{localStorage.setItem('eakha_data',JSON.stringify(D));ds.tahun=2026;ds.bulan=4;ds.D=D;ds.savedAt=new Date().toISOString();ds.reason='FULL TC AUDIT RULES + MC HRMIS CHECK APRIL 2026';localStorage.setItem('eakha_dataset_2026_4',JSON.stringify(ds));localStorage.setItem('eakha_last_dataset_key','eakha_dataset_2026_4')}catch(e){}
try{if(typeof renderMaster==='function')renderMaster(null);if(typeof renderDash==='function')renderDash();if(typeof updFlags==='function')updFlags()}catch(e){}
window.AUDIT_TC_RULES_REPORT_APRIL_2026={counts,sample,missingMC,missingHR,unmatchedMC,unmatchedHR};console.table(counts);console.table(sample);console.log('MC missing');console.table(missingMC);console.log('HRMIS missing');console.table(missingHR);console.log('MC unmatched');console.table(unmatchedMC);console.log('HRMIS unmatched');console.table(unmatchedHR);alert('Audit TC siap. SAH:'+counts.SAH+' LEWAT:'+counts.LEWAT+' OUT AWAL:'+counts.OUT_AWAL+' SEMAK:'+counts.SEMAK+' ABS:'+counts.ABS+' | MC missing:'+missingMC.length+' HRMIS missing:'+missingHR.length+'. Semak sebelum Simpan Snapshot.');
})();
